apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: artificial-insentience-
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 7654
      protocol: TCP
  health:
    disabled: false
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
  template:
    spec:
      containers:
        - name: artificial-insentience
          image: gcr.io/st-dev-252104/st-server
          imagePullPolicy: Always
          env:
            - name: ST_CLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: st-cloud-token
                  key: token
            - name: MATCHMAKER_URL
              value: asia-northeast1-st-dev-252104.cloudfunctions.net
