apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: singularity-trainer-
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 7654
      protocol: TCP
  health:
    disabled: false
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
  template:
    spec:
      containers:
        - name: singularity-trainer
          image: gcr.io/st-dev-252104/st-server
          imagePullPolicy: Always
