apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: singularity-trainer-
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 7654
      protocol: TCP
  health:
    disabled: false
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3
  template:
    spec:
      containers:
        - name: singularity-trainer
          image: gcr.io/st-dev-252104/st-server
          imagePullPolicy: Always
          env:
            - name: ST_CLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: st-cloud-token
                  key: token
            - name: PLAYER_1_USERNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['player_1_username']
            - name: PLAYER_2_USERNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['player_2_username']
            - name: PLAYER_1_TOKEN
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['player_1_token']
            - name: PLAYER_2_TOKEN
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['player_2_token']
