baseURL: "http://artificialinsentience.com/"
languageCode: en-gb
title: "AI: Artificial Insentience"
author:
  name: Isaac Poulton
disqusShortName: artificialinsentience

params:
  comments: true
  dateform: 2 Jan 2006
  dateformShort: 2 Jan 2006
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04 -0700"
  disableReadOtherPosts: false
  description: "AI: Artificial Insentience"
  keywords: "ai, game, artificial intelligence, artificial insentience"
  defaultTheme: dark

languages:
  en:
    title: ai://artificial_insentience
    callToAction: Create your AI
    keywords: ""
    copyright: ""
    readOtherPosts: Read other posts
    params:
      logo:
        logoText: "AI: Artificial Insentience"
        logoHomeLink: /
menu:
  main:
    - identifier: blog
      name: Dev Blog
      url: /posts
    - identifier: press_kit
      name: Press Kit
      url: /press_kit
